### ISSUE TITLE
3rd Person Kamera

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#1]
Die Kameraperspektive sollte so verschoben werden wie im folgenden Bild:
https://greatlakeside.de/index.php?attachment/482-20161001231526-1-jpg/

In Fahrzeugen darf aber die normale 3rd Person Perspektive angewendet werden.

**Comment by Veckt0r** [comment]
Würde FPS only außer in Fahrzeugen TPS erlauben

**Comment by Whitetex** [comment]
Das ist so ne sache da viele mit fps nich klar kommen und je nach Kleidung auch zu visuellen Fehlern kommen kann kann man probieren ggf sollte man später noch ne Umfrage machen

**Comment by schnuffi-carter** [comment]
Später wieder aufgerollt
