### ISSUE TITLE
ChopChop

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#2]
ChopChop

**Comment by schnuffi-carter** [comment]
Wie soll mit dem ChopChop interagiert werden?
Wo soll interagiert werden?
Wie viel Geld bekommt man?
Kann Polizei Daten abfragen, wer zuletzt verkauft hat?
Und ggf. weitere Fragen

**Comment by Veckt0r** [comment]
Von den Daten abfragen halte ich Persönlich nichts, die Polizei sollte dort schon Streife fahren bzw. auf gut Glück dort jemanden antreffen.
Geld würde ich ein gewissen %satz nehmen vom Neupreis.
Interagieren? -> Fahrzeug vorfahren NPC anscrollen und verkaufen.

**Comment by Veckt0r** [comment]
20% vom NP

**Comment by schnuffi-carter** [comment]
Mit GPS-Tracker kann das Fahrzeug nicht verkauft werden.
ChopChop kann für einen gewissen Betrag versuchen einen GPS-Tracker zu entfernen. Siehe App: GPS-Tracker

**Comment by schnuffi-carter** [comment]
Nur Zivilisten können hier verkaufen.

Fahrzeuge können am Autoschieber "ChopChop" illegal verkauft werden.
Gewinn: 50 % des zuvor errechneten Verkaufspreises (für Verkauf aus Garage) des Fahrzeuges beim Fahrzeugerwerb.

Hat der Spieler ein Fahrzeug beim ChopChop verkauft, wird eine Verlaufsvariable akualisiert, welche UID und Menge der verkauften Fahrzeuge beinhaltet.
Polizisten können nun den Autoschieber normal befragen (50/50 Chance, Infos zu erhalten) oder mit Schmiergeld bezahlen 77 % Wahrscheinlichkeit dass alle Namen genannt werden.
Bei der Abfrage werden automatisch die genannten Spieler auf die Fahndungsliste geschrieben und die Polizei erhält auch Nachrichten, wer.

Abgeschlossen.
