### ISSUE TITLE
Smartphone Appverwaltung

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#23]
Apps hinzufügen
- Marktübersicht
- News (akteuelle News -> Journalisten)

App-Anordnung individuell anpassen?
Apps auch wieder entfernen können?
Apps kostenlos oder nicht?
Gelderstattung (50%, 25% des KP) bei Löschung/Entfernung einer App?

**Comment by schnuffi-carter** [comment]
App-Verwaltung möglich, das Entfernen der Apps (ggf. mit Rückerstattung) jedoch noch nicht

**Comment by schnuffi-carter** [comment]
Marktübersicht sowie Smarthome verfügbar. Ggf. folgen mit der Zeit noch weitere

**Comment by schnuffi-carter** [comment]
_forEachIndex / IDC anpassen

**Comment by Veckt0r** [comment]
Keine Gelderstattung

**Comment by schnuffi-carter** [comment]
Feststellen, warum sich der Dialog schliesst, wenn eine App gekauft wird.

**Comment by schnuffi-carter** [comment]
Gefixt. Ggf folgen weitere Apps.
+ GPS-Tracker

**Comment by schnuffi-carter** [comment]
App-Vorschlag: Logbuch
Diese App soll Daten nur Sitzungsweise speichern (missionNamespace) und ausgeführte Aktionen sichern.
Z.B. eigenständig jemanden auf die Fahndungsliste gesetzt, Geld überwiesen, Nachrichten erhalten, Daten gespeichert, beim Autoschieber verkauft, Items verarbeitet, ...

Reine Übersichtlichkeit (auch um Fehler später ggf. finden zu können)

**Comment by Veckt0r** [comment]
Wieso dann nur Sitzungsweise da kann man genau sogut den großen Log für nehmen der perm. speichert

**Comment by schnuffi-carter** [comment]
App-Vorschlag: Logbuch wurde anderweitig umgesetzt.

Neue App für Fraktionen unter Fraktionssysteme: Notrufverwaltungssystem um eingegangene Notrufe zu verwalten (in Arbeit nehmen, pausieren, löschen)
![20170709212429_1](https://user-images.githubusercontent.com/13561039/27996938-91cbda00-64ed-11e7-8f18-5d8b53234ace.jpg)
![20170709212406_1](https://user-images.githubusercontent.com/13561039/27996942-91cfa72a-64ed-11e7-8242-2e2b5d33571f.jpg)
![20170709212341_1](https://user-images.githubusercontent.com/13561039/27996943-91d5bca0-64ed-11e7-9909-752ad03f61dc.jpg)
![20170709212336_1](https://user-images.githubusercontent.com/13561039/27996939-91ce2b2a-64ed-11e7-9205-5db1ffd08c23.jpg)
![20170709212332_1](https://user-images.githubusercontent.com/13561039/27996941-91cf5b08-64ed-11e7-8643-2e594840cf3e.jpg)
![20170709212301_1](https://user-images.githubusercontent.com/13561039/27996940-91cf0e32-64ed-11e7-8fd9-d3e8d8152ce2.jpg)

**Comment by schnuffi-carter** [comment]
Apps können erworben aber nicht entfernt werden, was auch ausreicht.

Abgeschlossen.
