### ISSUE TITLE
Grappler

### ISSUE THREAD

**Issue by Michail-Iwanow** [November-Bravo/Life-Mission-oeffentlich#25]
Die Polizei sollte die Möglichkeit bekommen, flüchtende Fahrzeuge, ohne sie zu Explosion zu bringen, anzuhalten. 

Eine ähnliche Entwicklung gibt es in RL schon:
https://www.youtube.com/watch?v=edmmg9Zf51E

Evt ist es möglich per Ace-Abschleppfunktion ein Auto so zu erfassen wenn es zB in 45° max 5 m von der Front des Polizeiautos entfernt ist. Auch könnte der näheste Reifen zerstört werden.

**Comment by schnuffi-carter** [comment]
Was für ein Gegenstand soll als Attachment am Fahrzeug genommen werden? - mhmm

**Comment by Veckt0r** [comment]
Habe bereits mit Modder gesprochen, zuviel Aufwand, man müsste für jedes Fahrzeuge ein Attachment Modden
