### ISSUE TITLE
Alarmsystem für Housing

### ISSUE THREAD

**Issue by Veckt0r** [November-Bravo/Life-Mission-oeffentlich#33]
Idee: Per Smartphone kann man eine App Namens XXX für XXX € kaufen.
Diese schaltet für das eigene Haus ein Alarmsystem frei.
Man wird also per ?hint? benachrichtigt wenn jemand probiert das Schloss zu knacken

Auf mehrere Häuser anwendbar?

Ggf. als Anregung:
https://native-network.net/forum/thread/3071-tutorial-alarm-system-f%C3%BCr-das-housing-system/?postID=68057#post68057

**Comment by schnuffi-carter** [comment]
Ich würde es wenn auf allen Häusern anwenden wollen.

**Comment by schnuffi-carter** [comment]
Oder man bindet es als Smart-Home ein mit Fernverwaltung von Häusern (vereinfachte Verwaltung mit weniger Möglichkeiten)

**Comment by schnuffi-carter** [comment]
Integriert in 4 Stufen:
- Stufe 0: Standard, kein Alarmsystem/Schutz, kein Alarm
- Stufe 1: Aufrüstung kostet, 20 %ige meldechance, lauter Alarm
- Stufe 2: Aufrüstung kostet, 50 %ige meldechance, lauter Alarm
- Stufe 3: Aufrüstung kostet, höchste aktuelle Sicherheitsstufe, 80 %ige meldechance, stiller Alarm

**Comment by schnuffi-carter** [comment]
Abgeschlossen
