### ISSUE TITLE
Häuserbenennung

### ISSUE THREAD

**Issue by Veckt0r** [November-Bravo/Life-Mission-oeffentlich#36]
Häuser sollen beim Kauf benannt werden können.
Das auf der Spieler Map der eigene Name vom Haus steht.

Beispiel:
Hauskauf -> Popup: Benenne dein Haus: XXX -> Auf Spielerkarte Hausmarker -> XXX

**Comment by schnuffi-carter** [comment]
Anzeigename auf Karte:
"Datenbank-ID - SmartHome inaktiv"

"SmartHome inaktiv" kann ersetzt werden mit einem individuellen maximal 12 Zeichen langen Namen. Name wird automatisch heruntergekürzt oder es werden ungültige Zeichen entfernt, wie Doppelpunkte (" : ").

Siehe auch Alarmsystem

**Comment by schnuffi-carter** [comment]
# Veckt0r commented 17 days ago • edited

Idee: Per Smartphone kann man eine App Namens XXX für XXX € kaufen.
Diese schaltet für das eigene Haus ein Alarmsystem frei.
Man wird also per ?hint? benachrichtigt wenn jemand probiert das Schloss zu knacken

Auf mehrere Häuser anwendbar?

Ggf. als Anregung:
https://native-network.net/forum/thread/3071-tutorial-alarm-system-f%C3%BCr-das-housing-system/?postID=68057#post68057

 # schnuffi-carter commented 17 days ago

Ich würde es wenn auf allen Häusern anwenden wollen.

 # schnuffi-carter commented 17 days ago

Oder man bindet es als Smart-Home ein mit Fernverwaltung von Häusern (vereinfachte Verwaltung mit weniger Möglichkeiten)

 # schnuffi-carter commented 4 days ago • edited

Integriert in 4 Stufen:

    Stufe 0: Standard, kein Alarmsystem/Schutz, kein Alarm
    Stufe 1: Aufrüstung kostet, 20 %ige meldechance, lauter Alarm
    Stufe 2: Aufrüstung kostet, 50 %ige meldechance, lauter Alarm
    Stufe 3: Aufrüstung kostet, höchste aktuelle Sicherheitsstufe, 80 %ige meldechance, stiller Alarm

Verwaltbar über die Smartphone-App "Smart Home".


**Abgeschlossen**
