### ISSUE TITLE
App: GPS Tracker

### ISSUE THREAD

**Issue by Veckt0r** [November-Bravo/Life-Mission-oeffentlich#38]
Idee:
Eine App womit man sein Auto per GPS Tracken kann.
In der App könnte alle 10 sek. die Position des Fahrzeuges per Grid angezeigt werden.
Oder man lässt das Auto auf der Map ersichtlich werden.
Frage:
Noch mit einfügen das man das Auto mit der App "abschalten" kann bzw den Motor deaktivieren bzw zu zerstören.

Klären:
Ob für einzelne Autos dauerhaft anwendbar

**Comment by schnuffi-carter** [comment]
- Positionsanzeige des jeweiligen Fahrzeuges als Grid (mapGridPosition)
- Nur pro Serverperiode, nicht permanent
- App-Kosten: 50.000 €
-- Je nach Fahrzeugart/-klasse einen Betrag für die jewilige Ortungsfunktion von 500€ - 15.000€
-- Gebühren sind nach jedem Ausparken für das jeweilige Fahrzeug, wenn GPS-Ortung verwendet werden soll, wieder fällig
- Motor nicht abschaltbar, Fahrzeug aber abschließbar
- Position des Fahrzeuges der Polizei als Notruf übermitteln
-- Ein "Golf GTI" mit der Lackierung "Rot" wurde von "Vecktor" gestohlen gemeldet. Dieses befindet sich auf Grund GPS-Ortung in dem Planquadranten "123 456". Bitte machen sie das Fahrzeug ausfindig und leiten sie notwendige Maßnahmen für weitere Ermittlungen ein.
-- Oder so ein ähnlicher Text
- GPS-Ortungsgerät kann beim ChopChop für einen gewissen Betrag entfernt werden, bzw. es wird vesucht zu entfernen
-- 50/50-Chance, ob erfolgreich oder fehlgeschlagen:
--- Bei Erfolg: Fahrzeug kann verkauft werden
--- Bei Misserfolg: Meldung an Polizei und Fahrzeugeigentümer (wenn online), wo sich das Fahrzeug befindet (ggf. mit Angabe welcher ChopChop

**Comment by Whitetex** [comment]
Finde ich gut

**Comment by Michail-Iwanow** [comment]
Wenn Polizei Meldung über gestohlenes Fahrzeug erhält, wird das Fahrzeug auch für die Polizei sichtbar. (Update alle 10 sek) 
Wenn man als Polizei eingeloggt ist erhält man temp zugang zur App. Das Fahrzeug kann manuell wieder aus der App entfernt werden (wenn zB an Besitzer überstellt)

**Comment by Michail-Iwanow** [comment]
Außerdem sollte das jeweilige Grid auch auf der Karte markiert werden. (Ein Punkt in der Mitte des Grids)

**Comment by schnuffi-carter** [comment]
GPS-Tracker eingebunden. ChopChop fehlt noch.

Tracker:
- Mit virtuellem Item Fahrzeug via GPS und zugehöriger Smartphone App verfolgen (Gridanzeige bei Fahrzeugsuswahl in Auflistung, bei Auswahl ungefähre Distanz von aktueller Spielerpos)
- Getracktes Fahrzeug kann aus der Ferne auf- oder abgeschlossen werden, wenn der Spieler Fahrzeugschlüssel besitzt und es nicht aufgebrochen hat
+ Schlüsselinhaber können Fahrzeug bei Polizei zur Fahndung ausschreiben und Fahndung wieder zurückrufen (keine Kosten dafür)
- Auflistung nur der Fahrzeuge, die einen GPS Tracker haben

**Comment by schnuffi-carter** [comment]
ChopChop fertiggestellt.

Abgeschlossen.
