### ISSUE TITLE
Airdrop/Waffenlieferung

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#39]
Keine automatisierten Airdrops, sondern Spieler/Unternehmen können diese Anforden für einen Betrag, der je nach Lieferungsart (klein, mittel, groß und gigantisch), bezahlen.
Polizisten würden eine "geheime" Meldung erhalten "Interpol hat durch einen Informanten erfahren, dass bei der Stadt/beim Planquadrant 123 456 eine Waffenlieferung erfolgen wird". Zivilisten erhalten eine ähnliche Meldung.

So ein Airdrop kann nur angefordert werden, wenn 
- genug Spieler online sind
- der Server schon mindestens eine gewisse Zeit online ist
- vorher angeforderte Waffenlieferungen abgeschlossen wurden
- etwa alle 30 Minuten möglich

Eine Waffenlieferung verschwindet nach Anlieferung nach 10 Minuten, oder wenn leer.

**Comment by Veckt0r** [comment]
Unnötig, wenn alle eine Nachricht darüber bekommen.
Fördert nur Supportfälle wegen RDM weil alle auf den Drop geiern und sich gegenseitig abknallen

**Comment by schnuffi-carter** [comment]
Pausiert, da es in einer Art von "Battle Royal" enden könnte/rdm.
Bessere Überlegung, wie es ablaufen sollte bzw. angekündigt wird. Und und und

**Comment by Whitetex** [comment]
Halte da auch nicht viel von
