### ISSUE TITLE
OrbatViewer

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#4]
OrbatViewer

**Comment by schnuffi-carter** [comment]
Referenz: https://community.bistudio.com/wiki/ORBAT_Viewer

**Comment by schnuffi-carter** [comment]
- [ ] Farmrouten in Baumansicht darstellen
- [ ] Features & Funktionen Kategorisiert erklären
- [ ] Teamstruktur darstellen

Ggf. Vereinfachte Konfig via DB, die immer bei Serverstart ausgelesen und als Code als Broadcast raus geht

**Comment by Veckt0r** [comment]
Wieso alles in den Orbat?
Nicht einfacher per Webseitenverweis?

**Comment by schnuffi-carter** [comment]
Wird anders umgesetzt.... Details folgen bei Zeit.
