### ISSUE TITLE
Hotspot Bank

### ISSUE THREAD

**Issue by Michail-Iwanow** [November-Bravo/Life-Mission-oeffentlich#48]
Die Bank soll wie folgt laufen:
Jede Türe muss aufgebrochen werden. Dieser Vorgang sollte 1-2 Minuten pro Tür dauern. (Evt zufällige Zeiten?). Die Safetür kann entweder gehackt werden (Safe-Knacker - 10.000€)(10 Minuten) oder aufgebohrt werden (Spezialbohrer - 4500€)(5min aber 50% Chance des Scheiterns). 
Bei jedem Manipulationsvorgang (Türen öffnen/Safe öffnen) besteht eine 40% Chance, dass die Polizei einen stillen Alarm bekommt. Die Polizei kann die Türen/Safe einfach wieder verschließen (Sie müssen wieder aufgebrochen werden. Der Räuber hat keinen Schlüssel!). Ist der Safe gehackt, hat der Räuber die Möglichkeit ihn in der gleichen Serverperiode jederzeit zu öffnen. Ist der Safe aufgebohrt, nicht.
Bei der Bank sollte man 700.000 bis 2 Mio € bekommen.

**Comment by Veckt0r** [comment]
40% ist viel zu hoch

**Comment by Veckt0r** [comment]
Kommt auch drauf an wieviele Türen es werden.

**Comment by Veckt0r** [comment]
40% ist zu viel, kommt drauf an wieviele Türen es sind.
Die gesamten Türen außer der Tresor an sich sollten schon ohne Alarm möglich sein und dies ist bei 40% nicht gegeben.
Beim Tresor kann ruhig immer nen Alarm losgehen

**Comment by schnuffi-carter** [comment]
Es könnte ja noch zusätzlich eine Art "Lost Knox" geben, wie Fort Knox aufbauen, vielleicht nicht so extrem, aber in der Art. Das könnte dann als Wertstofflager dienen für Gold, Schmuck, teils Geldpapiere oder anderes. 
Diese sollte nur einmal die Periode ausraubbar sein und eine Mindestanzahl von Polizisten müsse anwesend sein.

Normale Banken haben ausschließlich Geld. Bei diesen würde ich mich nach den oberen Vorschlag richten.

Nur eine zusätzliche Idee, kein muss.

**Comment by schnuffi-carter** [comment]
Verschoben nach https://github.com/November-Bravo/Life-Mission-oeffentlich/issues/9
