### ISSUE TITLE
Gefängnis

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#6]
Gefängnis mit notwendigen Funktionen einrichten

Wird eine Person im Gefängnis eingebuchtet, dann werden ihm folgende Sachen weggenommen:

    Illegale virtuelle Items
    Scharfe/Spitze Items (Seitenschneider, andere Werkzeuge)
    Aktuell ausgerüstete Waffen (falls vorher nicht abgenommen)
    Im Inventar (Rucksack, Weste und Uniform) vorhandene Gegenstände wie Magazine, abgelegte Waffen oder ortbare Geräte (GPS, Radio)

Beschlagnahmte Gegenstände werden weder nach dem Entlassen zurückgegeben, noch können sich diese zurück geholt werden. Der Wert der beschlagnahmten Gegenstände wird ebenfalls nicht ermittelt und auf das Unternehmenskonto überwiesen, da die Person vorher durchsucht hätte werden können.

**Comment by schnuffi-carter** [comment]
@November-Bravo/private-repo-access

**Comment by Michail-Iwanow** [comment]
Tätigkeiten für Gefangene?
zB: Müll durchwühlen und evt impro-Pistole bauen
oder: Steine kloppen um Haftzeit zu verringern (Haft dann doppelt so schnell vorbei?)

**Comment by schnuffi-carter** [comment]
Beendet.
Tätigkeiten kommen mit der Zeit, wenn erforderlich.
