### ISSUE TITLE
Go on Duty Funktion

### ISSUE THREAD

**Issue by Michail-Iwanow** [November-Bravo/Life-Mission-oeffentlich#66]
Kann man eine Funktion einfügen damit gewhitelistete Polizei und Medic Mitglieder von Ziv ohne in die Lobby wechseln zu müssen auf ihre Seite switchen können?

Also zB Civ>West

In Zeus kann man so eine Funktion nutzen, ergo muss es einen Command dafür geben. 
Es würde die Sache erleichtern wenn zB ein medic der grad als ziv spielt sieht: Alle anderen medics sind off, dann gehe ich halt in den dienst.

**Comment by schnuffi-carter** [comment]
https://community.bistudio.com/wiki/selectPlayer

https://community.bistudio.com/wiki/Team_Switch

**Comment by schnuffi-carter** [comment]
Nach meiner Meinung ist diese Funktion überflüssig und auch nicht realisierbar, da einige Variablen festgeschrieben sind und nicht im Spiel verändert werden können (z.B. Coplevel). Es würde einen auch nur eine Minute ersparen, und diese Zeit kann man opfern.
Closed
