### ISSUE TITLE
Lobbyhoppen 

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#7]
Whitetex und ich sind uns einig das die Position eines Spielers während einer Serverperiode gespeichert werden soll und erst nach Serverrestart oder nach Tod das Spawnmenü wieder verfügbar sein soll.
Damit verhindern wir das oben genannte Lobbyhoppen

Marco

**Comment by Veckt0r** [comment]
Jap sollte die ganze Periode gespeichert werden

**Comment by Veckt0r** [comment]
Abfrage der Position ale 60 Sek + zusätzlich wenn ESC gedrückt wird.

**Comment by schnuffi-carter** [comment]
Letzte Position des Spielers im uiNameSpace des Servers/des HCs speichern. Eine Blacklist für Orte festlegen:

    Wohnhäuser
    HQs
    Hotspots (später Banken, Verarbeiter- und Händlerorte, ...)

**Comment by schnuffi-carter** [comment]
Abgeschlossen.
Alle 60 Sekunden, oder bei Verlassen oder Speichern wird die Spielerposition gespeichert.
Spawnen tut der Spieler dann in der nächstgelegenenen Stadt und an einem zufälligen Ort in dieser Stadt.
