### ISSUE TITLE
Animationsauswahl

### ISSUE THREAD

**Issue by schnuffi-carter** [November-Bravo/Life-Mission-oeffentlich#8]
"Können wir dem ACE-Animationsmenü mit den Handsignalen andere Animationen anfügen?"

Man muss mir nur die Animationen einmal als möglichen Anzeigenamen nennen und den Klassennamen aus der Konfig

**Comment by schnuffi-carter** [comment]
![20170515214808_1](https://cloud.githubusercontent.com/assets/13561039/26092221/081d05d4-3a10-11e7-823c-1efaaf478178.jpg)

**Comment by Veckt0r** [comment]
Welche Animationen werden denn gebraucht die Sinnvoll sind und nicht nur der "Unterhaltung" dienen?

**Comment by schnuffi-carter** [comment]
Bitte um Rückmeldung anderer, ansonsten close

**Comment by schnuffi-carter** [comment]
Close, wegen keiner Rückmeldung.
